services:

  backend:
      build: backend    
      hostname: backend-hostname
      volumes:
        - ./backend:/app
      env_file: 
        - ./backend/.env  # Add this line to load environment variables from .env file
      ports:
        - "8000:8000"
      networks:
        - app-network
  frontend:
      build: frontend
      hostname: frontend-hostname
      volumes:
        - ./frontend:/app
      environment:
        - BACKEND_URL=http://backend-host:8000/submitodoitem
      ports:
        - "3000:3000"
      links:
        - backend
      depends_on:
        - backend
      networks:
        - app-network
     
networks:
  app-network: {}